FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc python3-dev libffi-dev libssl-dev \
    && rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip install --upgrade pip
RUN pip cache purge || true
RUN pip install --force-reinstall --no-cache-dir \
    evidently==0.6.4 pandas prometheus_client sniffio

EXPOSE 8001

CMD ["python", "drift_exporter.py"]
