# Dockerfile.drift
FROM python:3.10-slim

WORKDIR /app

COPY . .

# Upgrade pip to a stable version and install required packages with exact versions
RUN pip install --upgrade pip==23.0.1
RUN pip install --no-cache-dir evidently==0.6.4 pandas==2.3.3 prometheus_client==0.23.1 sniffio==1.3.1

# Expose Prometheus metrics port
EXPOSE 8001

# Run the drift exporter script
ENTRYPOINT ["python", "drift_exporter.py"]
